package com.Ansar.UserInterface;

import com.Ansar.DataModel.Services;
import com.Ansar.DataModel.ServicesType;
import com.Ansar.Database.GetDataFromDatabase;
import com.Ansar.Database.InsertDataInDatabase;
import com.Ansar.LinkedList.LinkedList;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class AddServices extends javax.swing.JPanel{
    GetDataFromDatabase getDataFromDatabase=new GetDataFromDatabase();
    DefaultTableModel model1,model3;

    /**
     * Creates new form AddServices
     */
    public AddServices() {
        initComponents();
        model1 =(DefaultTableModel) ServicesAll.getModel();
        model3=(DefaultTableModel) ServicesTypeAll.getModel();
        Multithreading_1 multithreading_1=new Multithreading_1();
        multithreading_1.start();
        Multithreading_2 multithreading_2=new Multithreading_2();
        multithreading_2.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        serviceName = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        addDataButon = new javax.swing.JButton();
        CustID = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        fileChose = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        serviceType = new javax.swing.JTextField();
        addDataButon1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        ServicesAll = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        ServicesTypeAll = new javax.swing.JTable();

        MainPanel.setBackground(new java.awt.Color(204, 204, 255));
        MainPanel.setPreferredSize(new java.awt.Dimension(650, 540));

        jPanel7.setBackground(new java.awt.Color(242, 247, 247));
        jPanel7.setToolTipText("Add Account's Data here in fields.");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Service Type    ");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Customer ID  ");

        addDataButon.setText("Add Data");
        addDataButon.setToolTipText("Click to add data.");
        addDataButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDataButonActionPerformed(evt);
            }
        });

        CustID.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("File Upload");
        jLabel17.setToolTipText("Hava Compleate Data File? Upload it here.");

        fileChose.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        fileChose.setForeground(new java.awt.Color(102, 102, 102));
        fileChose.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ansar\\Downloads\\icons8-file-30.png")); // NOI18N
        fileChose.setToolTipText("Click here to choose file.");
        fileChose.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        fileChose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fileChoseMouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Service Name   ");

        addDataButon1.setText("Add Data");
        addDataButon1.setToolTipText("Click to add data.");
        addDataButon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDataButon1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addComponent(serviceName, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(addDataButon)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel16)
                                                        .addComponent(CustID, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                                .addComponent(serviceType, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                                .addComponent(jLabel14)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                .addComponent(addDataButon1)
                                                .addGap(120, 120, 120)))
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addGap(107, 107, 107)
                                                .addComponent(jLabel17)
                                                .addGap(64, 64, 64))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(fileChose)
                                                .addGap(75, 75, 75))))
        );
        jPanel7Layout.setVerticalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel17)
                                        .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(serviceName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(addDataButon))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel16)
                                                        .addComponent(jLabel14)))
                                        .addComponent(fileChose))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(CustID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(serviceType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(addDataButon1))
                                .addContainerGap(61, Short.MAX_VALUE))
        );

        ServicesAll.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "Service ID", "Service Name"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                    false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ServicesAll.setToolTipText("All data of Services Table.");
        jScrollPane1.setViewportView(ServicesAll);

        ServicesTypeAll.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "Service ID", "Service Type"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                    false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ServicesTypeAll.setToolTipText("All data of Service Type Table.");
        jScrollPane3.setViewportView(ServicesTypeAll);

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
                MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MainPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator1)
                                        .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(MainPanelLayout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );
        MainPanelLayout.setVerticalGroup(
                MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MainPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(152, 152, 152))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 650, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 547, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 3, Short.MAX_VALUE)
                                        .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 4, Short.MAX_VALUE)))
        );
    }// </editor-fold>

    private void addDataButonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        InsertDataInDatabase inDatabase=new InsertDataInDatabase();
        try {
            inDatabase.InsertServices(serviceName.getText());
            Multithreading_1 multithreading_1 = new Multithreading_1();
            multithreading_1.start();
        }catch(Exception e)
        {
            ImageIcon icon = new ImageIcon("images\\error.png");
            JOptionPane.showMessageDialog(null, "Enter Correct Values!", "Failed", JOptionPane.ERROR_MESSAGE,icon);
        }
    }

    private void fileChoseMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    class Multithreading_1 extends Thread{
        public void run() {
            model1.setRowCount(0);
            LinkedList<Services> servicesLinkedList=getDataFromDatabase.getServices();
            for (int count = 0; count < servicesLinkedList.size(); count++) {
                model1.addRow(new Object[]{servicesLinkedList.get(count).getServiceId(),servicesLinkedList.get(count).getServiceName()});
            }
        }
    }

    class Multithreading_2 extends Thread{
        public void run() {
            model3.setRowCount(0);
            LinkedList<ServicesType> servicesTypeLinkedList=getDataFromDatabase.getServicesType();
            for (int count = 0; count < servicesTypeLinkedList.size(); count++) {
                model3.addRow(new Object[]{servicesTypeLinkedList.get(count).getServiceId(),servicesTypeLinkedList.get(count).getServiceType()});
            }
        }
    }

    private void addDataButon1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        InsertDataInDatabase inDatabase=new InsertDataInDatabase();
        try {
            inDatabase.InsertServicesType(Integer.parseInt(CustID.getText().replace(" ", "")), serviceType.getText());
            Multithreading_2 multithreading_2 = new Multithreading_2();
            multithreading_2.start();
        }catch (Exception e)
        {
            ImageIcon icon = new ImageIcon("images\\error.png");
            JOptionPane.showMessageDialog(null, "Enter Correct Values!", "Failed", JOptionPane.ERROR_MESSAGE,icon);
        }
    }


    // Variables declaration - do not modify
    private javax.swing.JFormattedTextField CustID;
    public javax.swing.JPanel MainPanel;
    private javax.swing.JTable ServicesAll;
    private javax.swing.JTable ServicesTypeAll;
    private javax.swing.JButton addDataButon;
    private javax.swing.JButton addDataButon1;
    private javax.swing.JLabel fileChose;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField serviceName;
    private javax.swing.JTextField serviceType;
    // End of variables declaration
}
