package com.Ansar.UserInterface;

import com.Ansar.Database.GetDataFromDatabase;
import com.Ansar.Database.UpdateDataInDatabase;

import javax.swing.*;
import java.awt.*;
import java.awt.image.BufferedImage;

public class Home extends javax.swing.JFrame {
    private GetDataFromDatabase getDataFromDatabase=new GetDataFromDatabase();
    private BufferedImage image;
    private String userName;
    /**
     * Creates new form Home
     */
    public Home(BufferedImage image,String userName) {
        this.image=image;
        this.userName=userName;
        initComponents();
        setColor(btn_2);
        ind_2.setOpaque(true);
        resetColor(new JPanel[]{btn_2,btn_3,btn_4}, new JPanel[]{ind_2,ind_3, ind_4});

    }

    public Home() {

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        MenuButtonGroup = new javax.swing.ButtonGroup();
        OptionsMenu = new javax.swing.ButtonGroup();
        side_pane = new javax.swing.JPanel();
        btn_2 = new javax.swing.JPanel();
        ind_2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btn_3 = new javax.swing.JPanel();
        ind_3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btn_4 = new javax.swing.JPanel();
        ind_4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        RollbackLabl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        CommitLabl = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ViewDataButton = new javax.swing.JRadioButton();
        InsertDataButton = new javax.swing.JRadioButton();
        UpdateDataButton = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();
        btn_exit = new javax.swing.JLabel();
        userNameImage = new javax.swing.JLabel();
        userNameText = new javax.swing.JLabel();
        MenuPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        showAccounts = new javax.swing.JRadioButton();
        showBills = new javax.swing.JRadioButton();
        showComments = new javax.swing.JRadioButton();
        showCustomers = new javax.swing.JRadioButton();
        showEmployees = new javax.swing.JRadioButton();
        showOrders = new javax.swing.JRadioButton();
        showPayments = new javax.swing.JRadioButton();
        showServices = new javax.swing.JRadioButton();
        MainPanel = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side_pane.setBackground(new java.awt.Color(23, 35, 51));
        side_pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_2.setBackground(new java.awt.Color(23, 35, 51));
        btn_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_2MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_2MouseReleased(evt);
            }
        });
        btn_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_2KeyPressed(evt);
            }
        });

        ind_2.setOpaque(false);
        ind_2.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_2Layout = new javax.swing.GroupLayout(ind_2);
        ind_2.setLayout(ind_2Layout);
        ind_2Layout.setHorizontalGroup(
                ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_2Layout.setVerticalGroup(
                ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Exit");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btn_2Layout = new javax.swing.GroupLayout(btn_2);
        btn_2.setLayout(btn_2Layout);
        btn_2Layout.setHorizontalGroup(
                btn_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(btn_2Layout.createSequentialGroup()
                                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 42, Short.MAX_VALUE))
        );
        btn_2Layout.setVerticalGroup(
                btn_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(btn_2Layout.createSequentialGroup()
                                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(btn_2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        side_pane.add(btn_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 120, -1));

        btn_3.setBackground(new java.awt.Color(23, 35, 51));
        btn_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_3MousePressed(evt);
            }
        });

        ind_3.setOpaque(false);
        ind_3.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_3Layout = new javax.swing.GroupLayout(ind_3);
        ind_3.setLayout(ind_3Layout);
        ind_3Layout.setHorizontalGroup(
                ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_3Layout.setVerticalGroup(
                ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Home");

        javax.swing.GroupLayout btn_3Layout = new javax.swing.GroupLayout(btn_3);
        btn_3.setLayout(btn_3Layout);
        btn_3Layout.setHorizontalGroup(
                btn_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(btn_3Layout.createSequentialGroup()
                                .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jLabel10)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        btn_3Layout.setVerticalGroup(
                btn_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(btn_3Layout.createSequentialGroup()
                                .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(btn_3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        side_pane.add(btn_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 120, -1));

        btn_4.setBackground(new java.awt.Color(23, 35, 51));
        btn_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_4MousePressed(evt);
            }
        });

        ind_4.setOpaque(false);
        ind_4.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_4Layout = new javax.swing.GroupLayout(ind_4);
        ind_4.setLayout(ind_4Layout);
        ind_4Layout.setHorizontalGroup(
                ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_4Layout.setVerticalGroup(
                ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Profile");

        javax.swing.GroupLayout btn_4Layout = new javax.swing.GroupLayout(btn_4);
        btn_4.setLayout(btn_4Layout);
        btn_4Layout.setHorizontalGroup(
                btn_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(btn_4Layout.createSequentialGroup()
                                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jLabel11)
                                .addGap(0, 45, Short.MAX_VALUE))
        );
        btn_4Layout.setVerticalGroup(
                btn_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(btn_4Layout.createSequentialGroup()
                                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(btn_4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        side_pane.add(btn_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 120, -1));

        getContentPane().add(side_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 590));

        jPanel2.setBackground(new java.awt.Color(71, 120, 197));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 950, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 950, 50));

        jPanel3.setBackground(new java.awt.Color(71, 120, 197));
        jPanel3.setForeground(new java.awt.Color(71, 120, 197));

        jPanel4.setBackground(new java.awt.Color(120, 168, 252));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(84, 127, 206));

        RollbackLabl.setIcon(new javax.swing.ImageIcon("images\\icons8-rollback-25 (1).png")); // NOI18N
        RollbackLabl.setToolTipText("Rollback in Database.");
        RollbackLabl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RollbackLablMouseClicked(evt);
            }
        });

        CommitLabl.setIcon(new javax.swing.ImageIcon("images\\icons8-database-view-25.png")); // NOI18N
        CommitLabl.setToolTipText("Commit in Database.");
        CommitLabl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CommitLablMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Options");
        jLabel12.setToolTipText("Select the following Operations to perform on listed tables.");

        ViewDataButton.setBackground(new java.awt.Color(84, 127, 206));
        OptionsMenu.add(ViewDataButton);
        ViewDataButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ViewDataButton.setForeground(new java.awt.Color(255, 255, 255));
        ViewDataButton.setText("View Data");
        ViewDataButton.setBorder(null);
        ViewDataButton.setFocusPainted(false);
        ViewDataButton.setFocusable(false);
        ViewDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewDataButtonActionPerformed(evt);
            }
        });

        InsertDataButton.setBackground(new java.awt.Color(84, 127, 206));
        OptionsMenu.add(InsertDataButton);
        InsertDataButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        InsertDataButton.setForeground(new java.awt.Color(255, 255, 255));
        InsertDataButton.setText("Insert Data");
        InsertDataButton.setBorder(null);
        InsertDataButton.setFocusPainted(false);
        InsertDataButton.setFocusable(false);
        InsertDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertDataButtonActionPerformed(evt);
            }
        });

        UpdateDataButton.setBackground(new java.awt.Color(84, 127, 206));
        OptionsMenu.add(UpdateDataButton);
        UpdateDataButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        UpdateDataButton.setForeground(new java.awt.Color(255, 255, 255));
        UpdateDataButton.setText("Update/Delete");
        UpdateDataButton.setBorder(null);
        UpdateDataButton.setFocusPainted(false);
        UpdateDataButton.setFocusable(false);
        UpdateDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateDataButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(ViewDataButton)
                                                        .addComponent(UpdateDataButton))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(InsertDataButton)
                                                .addGap(18, 18, 18)
                                                .addComponent(CommitLabl)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(RollbackLabl))
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel12)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGap(5, 5, 5)
                                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(InsertDataButton)
                                                        .addComponent(ViewDataButton))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(UpdateDataButton))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(RollbackLabl)
                                                        .addComponent(CommitLabl))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 85, 300, 130));

        btn_exit.setIcon(new javax.swing.ImageIcon("images\\icons8_Exit_25px.png")); // NOI18N
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_exitMousePressed(evt);
            }
        });
        jPanel4.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 24, -1, 46));

        userNameImage.setIcon(new javax.swing.ImageIcon(image)); // NOI18N
        jPanel4.add(userNameImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 86, -1));

        userNameText.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        userNameText.setForeground(new java.awt.Color(255, 255, 255));
        userNameText.setText(userName);
        jPanel4.add(userNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, 30));

        MenuPanel.setBackground(new java.awt.Color(71, 120, 197));
        MenuPanel.setForeground(new java.awt.Color(71, 120, 197));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Table Menu");
        jLabel8.setToolTipText("Available table list.");

        showAccounts.setBackground(new java.awt.Color(71, 120, 197));
        MenuButtonGroup.add(showAccounts);
        showAccounts.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        showAccounts.setForeground(new java.awt.Color(255, 255, 255));
        showAccounts.setText("Account");
        showAccounts.setBorder(null);
        showAccounts.setFocusPainted(false);
        showAccounts.setFocusable(false);
        showAccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAccountsActionPerformed(evt);
            }
        });

        showBills.setBackground(new java.awt.Color(71, 120, 197));
        MenuButtonGroup.add(showBills);
        showBills.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        showBills.setForeground(new java.awt.Color(255, 255, 255));
        showBills.setText("Bills");
        showBills.setBorder(null);
        showBills.setFocusPainted(false);
        showBills.setFocusable(false);
        showBills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showBillsActionPerformed(evt);
            }
        });

        showComments.setBackground(new java.awt.Color(71, 120, 197));
        MenuButtonGroup.add(showComments);
        showComments.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        showComments.setForeground(new java.awt.Color(255, 255, 255));
        showComments.setText("Comments");
        showComments.setBorder(null);
        showComments.setFocusPainted(false);
        showComments.setFocusable(false);
        showComments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showCommentsActionPerformed(evt);
            }
        });

        showCustomers.setBackground(new java.awt.Color(71, 120, 197));
        MenuButtonGroup.add(showCustomers);
        showCustomers.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        showCustomers.setForeground(new java.awt.Color(255, 255, 255));
        showCustomers.setText("Customers");
        showCustomers.setBorder(null);
        showCustomers.setFocusPainted(false);
        showCustomers.setFocusable(false);
        showCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showCustomersActionPerformed(evt);
            }
        });

        showEmployees.setBackground(new java.awt.Color(71, 120, 197));
        MenuButtonGroup.add(showEmployees);
        showEmployees.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        showEmployees.setForeground(new java.awt.Color(255, 255, 255));
        showEmployees.setText("Employee");
        showEmployees.setBorder(null);
        showEmployees.setFocusPainted(false);
        showEmployees.setFocusable(false);
        showEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showEmployeesActionPerformed(evt);
            }
        });

        showOrders.setBackground(new java.awt.Color(71, 120, 197));
        MenuButtonGroup.add(showOrders);
        showOrders.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        showOrders.setForeground(new java.awt.Color(255, 255, 255));
        showOrders.setText("Orders");
        showOrders.setBorder(null);
        showOrders.setFocusPainted(false);
        showOrders.setFocusable(false);
        showOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showOrdersActionPerformed(evt);
            }
        });

        showPayments.setBackground(new java.awt.Color(71, 120, 197));
        MenuButtonGroup.add(showPayments);
        showPayments.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        showPayments.setForeground(new java.awt.Color(255, 255, 255));
        showPayments.setText("Payments");
        showPayments.setBorder(null);
        showPayments.setFocusPainted(false);
        showPayments.setFocusable(false);
        showPayments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPaymentsActionPerformed(evt);
            }
        });

        showServices.setBackground(new java.awt.Color(71, 120, 197));
        MenuButtonGroup.add(showServices);
        showServices.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        showServices.setForeground(new java.awt.Color(255, 255, 255));
        showServices.setText("Services");
        showServices.setBorder(null);
        showServices.setFocusPainted(false);
        showServices.setFocusable(false);
        showServices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showServicesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
                MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MenuPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(showOrders)
                                        .addComponent(showAccounts, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(showBills)
                                        .addComponent(showComments)
                                        .addComponent(showCustomers)
                                        .addComponent(showEmployees)
                                        .addComponent(showPayments)
                                        .addComponent(showServices)
                                        .addComponent(jLabel8))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuPanelLayout.setVerticalGroup(
                MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MenuPanelLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(showAccounts, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(showBills)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(showComments)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(showCustomers)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(showEmployees)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(showOrders)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(showPayments)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(showServices)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(MenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(MenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(106, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 300, 540));

        MainPanel.setBackground(new java.awt.Color(204, 204, 255));

        jPanel7.setBackground(new java.awt.Color(242, 247, 247));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Wellcome ");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(501, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel14)
                                .addContainerGap(116, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
                MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        MainPanelLayout.setVerticalGroup(
                MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MainPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(374, Short.MAX_VALUE))
        );

        getContentPane().add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 650, 540));

        pack();
    }// </editor-fold>

    private void btn_3MousePressed(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        setColor(btn_3);
        ind_3.setOpaque(true);
        resetColor(new JPanel[]{btn_2,btn_4}, new JPanel[]{ind_2, ind_4});
    }

    private void btn_4MousePressed(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        setColor(btn_4);
        ind_4.setOpaque(true);
        resetColor(new JPanel[]{btn_2,btn_3}, new JPanel[]{ind_2,ind_3,});
    }

    int xx,xy;
    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        //drag this pane
        xx = evt.getX();
        xy = evt.getY();
    }

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:

        //source to drag
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }

    private void btn_exitMousePressed(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        this.setVisible(false);
        LoginScreen loginScreen=new LoginScreen();
        loginScreen.setVisible(true);
    }

    private void btn_2MouseReleased(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        setColor(btn_2);
        ind_2.setOpaque(true);
        resetColor(new JPanel[]{btn_3,btn_4}, new JPanel[]{ind_3, ind_4});
    }

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        System.exit(1);
    }

    private void btn_2MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        System.exit(1);
    }

    private void btn_2KeyPressed(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
        System.exit(1);
    }


    private void CommitLablMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        UpdateDataInDatabase updateDataInDatabase=new UpdateDataInDatabase();
        updateDataInDatabase.commit();
    }

    private void RollbackLablMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        UpdateDataInDatabase updateDataInDatabase=new UpdateDataInDatabase();
        updateDataInDatabase.rollBack();
    }


    private void ViewDataButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void InsertDataButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void UpdateDataButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }



    private void showAccountsActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(ViewDataButton.isSelected())
        {
            SeeAccount seeAccount=new SeeAccount();
            MainPanel.setLayout(new java.awt.BorderLayout());
            MainPanel.removeAll();
            MainPanel.add(seeAccount.MainPanel);
            MainPanel.validate();
        }
        else if(InsertDataButton.isSelected())
        {
            AddAccount addAccount=new AddAccount();
            MainPanel.setLayout(new java.awt.BorderLayout());
            MainPanel.removeAll();
            MainPanel.add(addAccount.MainPanel);
            MainPanel.validate();
        }
        else if(UpdateDataButton.isSelected())
        {
            UpdateOrDeleteAccount updateOrDeleteAccount=new UpdateOrDeleteAccount();
            MainPanel.setLayout(new java.awt.BorderLayout());
            MainPanel.removeAll();
            MainPanel.add(updateOrDeleteAccount.MainPanel);
            MainPanel.validate();
        }
    }

    private void showBillsActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(ViewDataButton.isSelected()) {
            SeeBills seeBills = new SeeBills();
            MainPanel.setLayout(new java.awt.BorderLayout());
            MainPanel.removeAll();
            MainPanel.add(seeBills.MainPanel);
            MainPanel.validate();
        }
        else if(InsertDataButton.isSelected())
        {
            AddBills addBills=new AddBills();
            MainPanel.setLayout(new java.awt.BorderLayout());
            MainPanel.removeAll();
            MainPanel.add(addBills.MainPanel);
            MainPanel.validate();
        }
        else if(UpdateDataButton.isSelected())
        {
            UpdateOrDeleteBills updateOrDeleteBills=new UpdateOrDeleteBills();
            MainPanel.setLayout(new java.awt.BorderLayout());
            MainPanel.removeAll();
            MainPanel.add(updateOrDeleteBills.MainPanel);
            MainPanel.validate();
        }
    }

    private void showCommentsActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(ViewDataButton.isSelected()) {
            SeeComment seeComment=new SeeComment();
            MainPanel.setLayout(new java.awt.BorderLayout());
            MainPanel.removeAll();
            MainPanel.add(seeComment.MainPanel);
            MainPanel.validate();
        }
        else if(InsertDataButton.isSelected())
        {
            AddComment addComment=new AddComment();
            MainPanel.setLayout(new java.awt.BorderLayout());
            MainPanel.removeAll();
            MainPanel.add(addComment.MainPanel);
            MainPanel.validate();

        }
        else if(UpdateDataButton.isSelected())
        {
            UpdateOrDeleteComment updateOrDeleteComment=new UpdateOrDeleteComment();
            MainPanel.setLayout(new java.awt.BorderLayout());
            MainPanel.removeAll();
            MainPanel.add(updateOrDeleteComment.MainPanel);
            MainPanel.validate();
        }

    }

    private void showCustomersActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(ViewDataButton.isSelected()) {
            SeeCustomer seeCustomer=new SeeCustomer();
            MainPanel.setLayout(new java.awt.BorderLayout());
            MainPanel.removeAll();
            MainPanel.add(seeCustomer.MainPanel);
            MainPanel.validate();
        }
        else if(InsertDataButton.isSelected())
        {
            AddCustomer addCustomer=new AddCustomer();
            MainPanel.setLayout(new java.awt.BorderLayout());
            MainPanel.removeAll();
            MainPanel.add(addCustomer.MainPanel);
            MainPanel.validate();
        }
        else if(UpdateDataButton.isSelected())
        {
            UpdateOrDeleteCustomers updateOrDeleteCustomers=new UpdateOrDeleteCustomers();
            MainPanel.setLayout(new java.awt.BorderLayout());
            MainPanel.removeAll();
            MainPanel.add(updateOrDeleteCustomers.MainPanel);
            MainPanel.validate();
        }

    }

    private void showEmployeesActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(ViewDataButton.isSelected()) {
            SeeEmployee seeEmployee=new SeeEmployee();
            MainPanel.setLayout(new java.awt.BorderLayout());
            MainPanel.removeAll();
            MainPanel.add(seeEmployee.MainPanel);
            MainPanel.validate();
        }
        else if(InsertDataButton.isSelected())
        {
            AddEmployee addEmployee=new AddEmployee();
            MainPanel.setLayout(new java.awt.BorderLayout());
            MainPanel.removeAll();
            MainPanel.add(addEmployee.MainPanel);
            MainPanel.validate();
        }
        else if(UpdateDataButton.isSelected())
        {
            UpdateOrDeleteEmployee updateOrDeleteEmployee=new UpdateOrDeleteEmployee();
            MainPanel.setLayout(new java.awt.BorderLayout());
            MainPanel.removeAll();
            MainPanel.add(updateOrDeleteEmployee.MainPanel);
            MainPanel.validate();
        }
    }

    private void showOrdersActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(ViewDataButton.isSelected()) {
            SeeOrder seeOrder=new SeeOrder();
            MainPanel.setLayout(new java.awt.BorderLayout());
            MainPanel.removeAll();
            MainPanel.add(seeOrder.MainPanel);
            MainPanel.validate();
        }
        else if(InsertDataButton.isSelected())
        {
            AddOrder addOrder=new AddOrder();
            MainPanel.setLayout(new java.awt.BorderLayout());
            MainPanel.removeAll();
            MainPanel.add(addOrder.MainPanel);
            MainPanel.validate();
        }
        else if(UpdateDataButton.isSelected())
        {
            UpdateOrDeleteOrder updateOrDeleteOrder=new UpdateOrDeleteOrder();
            MainPanel.setLayout(new java.awt.BorderLayout());
            MainPanel.removeAll();
            MainPanel.add(updateOrDeleteOrder.MainPanel);
            MainPanel.validate();
        }
    }

    private void showPaymentsActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(ViewDataButton.isSelected()) {
            SeePayment seePayment=new SeePayment();
            MainPanel.setLayout(new java.awt.BorderLayout());
            MainPanel.removeAll();
            MainPanel.add(seePayment.MainPanel);
            MainPanel.validate();
        }
        else if(InsertDataButton.isSelected())
        {
            AddPayment addPayment=new AddPayment();
            MainPanel.setLayout(new java.awt.BorderLayout());
            MainPanel.removeAll();
            MainPanel.add(addPayment.MainPanel);
            MainPanel.validate();
        }
        else if(UpdateDataButton.isSelected())
        {
            UpdateOrDeletePayment updateOrDeletePayment=new UpdateOrDeletePayment();
            MainPanel.setLayout(new java.awt.BorderLayout());
            MainPanel.removeAll();
            MainPanel.add(updateOrDeletePayment.MainPanel);
            MainPanel.validate();
        }
    }

    private void showServicesActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(ViewDataButton.isSelected()) {
            SeeServices seeServices=new SeeServices();
            MainPanel.setLayout(new java.awt.BorderLayout());
            MainPanel.removeAll();
            MainPanel.add(seeServices.MainPanel);
            MainPanel.validate();
        }
        else if(InsertDataButton.isSelected())
        {
            AddServices addServices=new AddServices();
            MainPanel.setLayout(new java.awt.BorderLayout());
            MainPanel.removeAll();
            MainPanel.add(addServices.MainPanel);
            MainPanel.validate();
        }
        else if(UpdateDataButton.isSelected())
        {
            UpdateOrDeleteServices updateOrDeleteServices=new UpdateOrDeleteServices();
            MainPanel.setLayout(new java.awt.BorderLayout());
            MainPanel.removeAll();
            MainPanel.add(updateOrDeleteServices.MainPanel);
            MainPanel.validate();

        }
    }



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }


    private void setColor(JPanel pane)
    {
        pane.setBackground(new Color(41,57,80));
    }

    private void resetColor(JPanel [] pane, JPanel [] indicators)
    {
        for(int i=0;i<pane.length;i++){
            pane[i].setBackground(new Color(23,35,51));

        } for(int i=0;i<indicators.length;i++){
        indicators[i].setOpaque(false);
    }

    }


    // Variables declaration - do not modify
    private javax.swing.JLabel CommitLabl;
    private javax.swing.JRadioButton InsertDataButton;
    private javax.swing.JPanel MainPanel;
    private javax.swing.ButtonGroup MenuButtonGroup;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.ButtonGroup OptionsMenu;
    private javax.swing.JLabel RollbackLabl;
    private javax.swing.JRadioButton UpdateDataButton;
    private javax.swing.JRadioButton ViewDataButton;
    private javax.swing.JPanel btn_2;
    private javax.swing.JPanel btn_3;
    private javax.swing.JPanel btn_4;
    private javax.swing.JLabel btn_exit;
    private javax.swing.JPanel ind_2;
    private javax.swing.JPanel ind_3;
    private javax.swing.JPanel ind_4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JRadioButton showAccounts;
    private javax.swing.JRadioButton showBills;
    private javax.swing.JRadioButton showComments;
    private javax.swing.JRadioButton showCustomers;
    private javax.swing.JRadioButton showEmployees;
    private javax.swing.JRadioButton showOrders;
    private javax.swing.JRadioButton showPayments;
    private javax.swing.JRadioButton showServices;
    private javax.swing.JPanel side_pane;
    private javax.swing.JLabel userNameImage;
    private javax.swing.JLabel userNameText;
    // End of variables declaration
}

