package com.Ansar.UserInterface;

import com.Ansar.DataModel.Account;
import com.Ansar.Database.DeleteInDatabase;
import com.Ansar.Database.GetDataFromDatabase;
import com.Ansar.Database.UpdateDataInDatabase;
import com.Ansar.LinkedList.LinkedList;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class UpdateOrDeleteAccount  extends javax.swing.JPanel{
    GetDataFromDatabase getDataFromDatabase=new GetDataFromDatabase();
    Account account;
    DefaultTableModel model1,model2;

    /**
     * Creates new form UpdateOrDeleteAccount
     */
    public UpdateOrDeleteAccount() {
        initComponents();
        editingButton.setVisible(false);
        updateButton.setVisible(false);
        deleteButton.setVisible(false);
        model1 =(DefaultTableModel) AccoutAll.getModel();
        model2=(DefaultTableModel) searchedAccount.getModel();
        Multithreading thread=new Multithreading();
        thread.start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        MainPanel = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        accDetails = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        accType = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        accCustID = new javax.swing.JFormattedTextField();
        updateButton = new javax.swing.JRadioButton();
        deleteButton = new javax.swing.JRadioButton();
        editingButton = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        AccoutAll = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        AccountTypeOrIDText = new javax.swing.JTextField();
        SearchAccountButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        searchedAccount = new javax.swing.JTable();

        MainPanel.setBackground(new java.awt.Color(204, 204, 255));

        jPanel7.setBackground(new java.awt.Color(242, 247, 247));
        jPanel7.setToolTipText("Account's Data here in fields.");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Account Details");

        accDetails.setEditable(false);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Account Type  ");

        accType.setEditable(false);
        accType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accTypeActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Customer ID  ");

        accCustID.setEditable(false);
        accCustID.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        updateButton.setBackground(new java.awt.Color(242, 247, 247));
        buttonGroup1.add(updateButton);
        updateButton.setText("Update");
        updateButton.setToolTipText("Click to update.");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setBackground(new java.awt.Color(242, 247, 247));
        buttonGroup1.add(deleteButton);
        deleteButton.setText("Delete");
        deleteButton.setToolTipText("click to delete.");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        editingButton.setBackground(new java.awt.Color(242, 247, 247));
        editingButton.setText("Enable Editing");
        editingButton.setToolTipText("Click to Edit Details.");
        editingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editingButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(accDetails))
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(deleteButton)
                                                .addComponent(updateButton)))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                        .addComponent(accType))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addComponent(accCustID, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addComponent(editingButton)
                                .addGap(216, 216, 216))
        );
        jPanel7Layout.setVerticalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel14)
                                        .addComponent(jLabel15)
                                        .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(accDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(accType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(accCustID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(editingButton))
                                .addGap(27, 27, 27)
                                .addComponent(updateButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteButton)
                                .addContainerGap(36, Short.MAX_VALUE))
        );

        AccoutAll.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "Account Number", "Account Detail", "Account Type", "Customer ID"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                    false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        AccoutAll.setToolTipText("All data of Account Table.");
        jScrollPane1.setViewportView(AccoutAll);

        jPanel8.setBackground(new java.awt.Color(242, 247, 247));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Enter Account ID            ");

        AccountTypeOrIDText.setToolTipText("Enter ID/Account Type to Search.");

        SearchAccountButton.setText("Search");
        SearchAccountButton.setFocusPainted(false);
        SearchAccountButton.setFocusable(false);
        SearchAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchAccountButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(AccountTypeOrIDText))
                                .addGap(18, 18, 18)
                                .addComponent(SearchAccountButton)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(AccountTypeOrIDText)
                                        .addComponent(SearchAccountButton))
                                .addContainerGap())
        );

        searchedAccount.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "Account Number", "Account Detail", "Account Type", "Customer ID"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                    false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(searchedAccount);

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
                MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MainPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane2)
                                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1))
                                .addContainerGap())
        );
        MainPanelLayout.setVerticalGroup(
                MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MainPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 663, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 6, Short.MAX_VALUE)
                                        .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 7, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 540, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>

    private void accTypeActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void SearchAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        GetDataFromDatabase getDataFromDatabase=new GetDataFromDatabase();
        try {
            account = getDataFromDatabase.getSingleAccount(Integer.parseInt(AccountTypeOrIDText.getText().replace(" ", "")));
            if (account != null) {
                model2.setRowCount(0);
                model2.addRow(new Object[]{account.getAccountNumber(), account.getAccountDetail(),
                        account.getAccountType(), account.getCustomerId()});
                accDetails.setText(account.getAccountDetail());
                accType.setText(account.getAccountType());
                accCustID.setText(String.valueOf(account.getCustomerId()));
                editingButton.setVisible(true);
            } else {
                model2.setRowCount(0);
                accDetails.setText(null);
                accType.setText(null);
                accCustID.setText(null);
                editingButton.setVisible(false);
                updateButton.setVisible(false);
                deleteButton.setVisible(false);
            }
        }catch(Exception e)
        {
            ImageIcon icon = new ImageIcon("images\\error.png");
            JOptionPane.showMessageDialog(null, e, "Failed", JOptionPane.ERROR_MESSAGE,icon);
            model2.setRowCount(0);
            accDetails.setText(null);
            accType.setText(null);
            accCustID.setText(null);
            editingButton.setVisible(false);
            updateButton.setVisible(false);
            deleteButton.setVisible(false);

        }
    }

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        UpdateDataInDatabase updateDataInDatabase=new UpdateDataInDatabase();
        try {
            boolean flag = updateDataInDatabase.UpdateInAccount(account.getAccountNumber(), accDetails.getText(), accType.getText(),
                    Integer.parseInt(accCustID.getText().replace(" ", "")));
            if (flag) {
                Multithreading thread = new Multithreading();
                thread.start();
            }
        }catch(Exception e)
        {
            ImageIcon icon = new ImageIcon("images\\error.png");
            JOptionPane.showMessageDialog(null, e, "Failed", JOptionPane.ERROR_MESSAGE,icon);
        }
    }

    private void editingButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(editingButton.isSelected())
        {
            accDetails.setEditable(true);
            accType.setEditable(true);
            accCustID.setEditable(true);
            updateButton.setVisible(true);
            deleteButton.setVisible(true);
        }
        else
        {
            accDetails.setEditable(false);
            accType.setEditable(false);
            accCustID.setEditable(false);
            updateButton.setVisible(false);
            deleteButton.setVisible(false);
        }
    }
    class Multithreading extends Thread{
        public void run() {
            model1.setRowCount(0);
            LinkedList<Account> accountLinkedList = getDataFromDatabase.getAccount();
            for (int count = 0; count < accountLinkedList.size(); count++) {
                model1.addRow(new Object[]{accountLinkedList.get(count).getAccountNumber(), accountLinkedList.get(count).getAccountDetail(),
                        accountLinkedList.get(count).getAccountType(), accountLinkedList.get(count).getCustomerId()});
            }
        }
    }
    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        DeleteInDatabase deleteInDatabase=new DeleteInDatabase();
        try
        {
        boolean flag=deleteInDatabase.DeleteInAccount(account.getAccountNumber());
        if(flag)
        {
            Multithreading thread=new Multithreading();
            thread.start();
        }}catch(Exception e)
        {
            ImageIcon icon = new ImageIcon("images\\error.png");
            JOptionPane.showMessageDialog(null, e, "Failed", JOptionPane.ERROR_MESSAGE,icon);
        }
    }


    // Variables declaration - do not modify
    private javax.swing.JTextField AccountTypeOrIDText;
    private javax.swing.JTable AccoutAll;
    public javax.swing.JPanel MainPanel;
    private javax.swing.JButton SearchAccountButton;
    private javax.swing.JFormattedTextField accCustID;
    private javax.swing.JTextField accDetails;
    private javax.swing.JTextField accType;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton deleteButton;
    private javax.swing.JCheckBox editingButton;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable searchedAccount;
    private javax.swing.JRadioButton updateButton;
    // End of variables declaration

}


