package com.Ansar.UserInterface;

import com.Ansar.DataModel.Comment;
import com.Ansar.Database.DeleteInDatabase;
import com.Ansar.Database.GetDataFromDatabase;
import com.Ansar.Database.UpdateDataInDatabase;
import com.Ansar.LinkedList.LinkedList;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class UpdateOrDeleteComment extends javax.swing.JPanel{
    GetDataFromDatabase getDataFromDatabase=new GetDataFromDatabase();
    Comment comment;
    DefaultTableModel model1,model2;
    /**
     * Creates new form UpdateOdDeleteComment
     */
    public UpdateOrDeleteComment() {
        initComponents();
        editingButton.setVisible(false);
        updateButton.setVisible(false);
        deleteButton.setVisible(false);
        model1 =(DefaultTableModel) CommentAll.getModel();
        model2=(DefaultTableModel) searchedResultTable.getModel();
        Multithreading thread=new Multithreading();
        thread.start();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        Comment_ID_DetailsText = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        CommentAll = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        searchedResultTable = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        custID = new javax.swing.JFormattedTextField();
        paymentID = new javax.swing.JFormattedTextField();
        commenrDetails = new javax.swing.JTextField();
        updateButton = new javax.swing.JRadioButton();
        deleteButton = new javax.swing.JRadioButton();
        editingButton = new javax.swing.JCheckBox();

        MainPanel.setBackground(new java.awt.Color(204, 204, 255));
        MainPanel.setPreferredSize(new java.awt.Dimension(650, 540));

        jPanel7.setBackground(new java.awt.Color(242, 247, 247));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Enter Comment ID        ");
        jLabel14.setToolTipText("");

        Comment_ID_DetailsText.setToolTipText("Enter ID/Details to search.");

        SearchButton.setText("Search");
        SearchButton.setFocusPainted(false);
        SearchButton.setFocusable(false);
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Comment_ID_DetailsText))
                                .addGap(18, 18, 18)
                                .addComponent(SearchButton)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Comment_ID_DetailsText)
                                        .addComponent(SearchButton))
                                .addContainerGap())
        );

        CommentAll.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "Comment ID", "Payment ID", "Customer ID", "Comment Details"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                    false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        CommentAll.setToolTipText("All data of Comment Table.");
        jScrollPane1.setViewportView(CommentAll);

        searchedResultTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "Comment ID", "Payment ID", "Customer ID", "Comment Details"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                    false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        searchedResultTable.setToolTipText("Search results.");
        jScrollPane2.setViewportView(searchedResultTable);

        jPanel8.setBackground(new java.awt.Color(242, 247, 247));
        jPanel8.setToolTipText("Add Account's Data here in fields.");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Comment Details");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Payment ID     ");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Customer ID ");

        custID.setEditable(false);
        custID.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        paymentID.setEditable(false);
        paymentID.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        paymentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentIDActionPerformed(evt);
            }
        });

        commenrDetails.setEditable(false);

        updateButton.setBackground(new java.awt.Color(242, 247, 247));
        updateButton.setText("Update");
        updateButton.setToolTipText("Click to update.");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setBackground(new java.awt.Color(242, 247, 247));
        deleteButton.setText("Delete");
        deleteButton.setToolTipText("click to delete.");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        editingButton.setBackground(new java.awt.Color(242, 247, 247));
        editingButton.setText("Enable Editing");
        editingButton.setToolTipText("Click to Edit Details.");
        editingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editingButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel8Layout.createSequentialGroup()
                                                .addComponent(updateButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(deleteButton)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel8Layout.createSequentialGroup()
                                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(commenrDetails))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(paymentID, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(27, 27, 27)
                                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(jPanel8Layout.createSequentialGroup()
                                                                .addComponent(custID, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, Short.MAX_VALUE)))
                                                .addGap(18, 18, 18)
                                                .addComponent(editingButton)
                                                .addGap(227, 227, 227))))
        );
        jPanel8Layout.setVerticalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel15)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(custID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(paymentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(commenrDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(editingButton))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(updateButton)
                                        .addComponent(deleteButton))
                                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
                MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MainPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1)
                                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        MainPanelLayout.setVerticalGroup(
                MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 650, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 540, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>
    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        GetDataFromDatabase getDataFromDatabase=new GetDataFromDatabase();
        try{
        comment=getDataFromDatabase.getSingleComment(Integer.parseInt(Comment_ID_DetailsText.getText().replace(" ","")));
        if(comment!=null)
        {
            model2.setRowCount(0);
            model2.addRow(new Object[]{comment.getCommentId(),comment.getPaymentId(),comment.getCustomerId(),comment.getCommentDetails()});
            paymentID.setText(String.valueOf(comment.getPaymentId()));
            custID.setText(String.valueOf(comment.getCustomerId()));
            commenrDetails.setText(comment.getCommentDetails());
            editingButton.setVisible(true);
        }
        else
        {
            model2.setRowCount(0);
            paymentID.setText(null);
            custID.setText(null);
            commenrDetails.setText(null);
            editingButton.setVisible(false);
            updateButton.setVisible(false);
            deleteButton.setVisible(false);
        }}catch(Exception e)
        {
            ImageIcon icon = new ImageIcon("images\\error.png");
            JOptionPane.showMessageDialog(null, e, "Failed", JOptionPane.ERROR_MESSAGE,icon);
            model2.setRowCount(0);
            paymentID.setText(null);
            custID.setText(null);
            commenrDetails.setText(null);
            editingButton.setVisible(false);
            updateButton.setVisible(false);
            deleteButton.setVisible(false);
        }
    }

    private void paymentIDActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        UpdateDataInDatabase updateDataInDatabase=new UpdateDataInDatabase();
        try{
        boolean flag=updateDataInDatabase.UpdateINComment(comment.getCommentId(),commenrDetails.getText(),Integer.parseInt(paymentID.getText().replace(" ","")),
                Integer.parseInt(custID.getText().replace(" ","")));
        if(flag)
        {
            Multithreading thread=new Multithreading();
            thread.start();
        }
        }catch(Exception e)
        {
            ImageIcon icon = new ImageIcon("images\\error.png");
            JOptionPane.showMessageDialog(null, e, "Failed", JOptionPane.ERROR_MESSAGE,icon);
        }
    }

    private void editingButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(editingButton.isSelected())
        {
            paymentID.setEditable(true);
            custID.setEditable(true);
            commenrDetails.setEditable(true);
            updateButton.setVisible(true);
            deleteButton.setVisible(true);
        }
        else
        {
            paymentID.setEditable(false);
            custID.setEditable(false);
            commenrDetails.setEditable(false);
            updateButton.setVisible(false);
            deleteButton.setVisible(false);
        }
    }

    class Multithreading extends Thread{
        public void run() {
            model1.setRowCount(0);
            LinkedList<Comment> commentLinkedList=getDataFromDatabase.getComment();
            for (int count = 0; count < commentLinkedList.size(); count++) {
                model1.addRow(new Object[]{commentLinkedList.get(count).getCommentId(),commentLinkedList.get(count).getPaymentId(),
                        commentLinkedList.get(count).getCustomerId(),commentLinkedList.get(count).getCommentDetails()});
            }
        }
    }

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        DeleteInDatabase deleteInDatabase=new DeleteInDatabase();
        boolean flag=deleteInDatabase.DeleteINComment(comment.getCommentId());
        if(flag)
        {
            Multithreading thread=new Multithreading();
            thread.start();
        }
    }


    // Variables declaration - do not modify
    private javax.swing.JTable CommentAll;
    private javax.swing.JTextField Comment_ID_DetailsText;
    public javax.swing.JPanel MainPanel;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTextField commenrDetails;
    private javax.swing.JFormattedTextField custID;
    private javax.swing.JRadioButton deleteButton;
    private javax.swing.JCheckBox editingButton;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JFormattedTextField paymentID;
    private javax.swing.JTable searchedResultTable;
    private javax.swing.JRadioButton updateButton;
    // End of variables declaration
}
